name: AIPowerPlugin
version: "${version}"
main: com.marcodluz.aipowerplugin.AIPowerPlugin
api-version: 1.20
author: marcodluz
description: AI Power Plugin for Minecraft
website: https://github.com/marcodluz/ai-power-plugin

commands:
  ai:
    description: Main AI command
    usage: /<command> [help|reload|config] or /<command> <message>
    permission: ai.use
    permission-message: You don't have permission to use this command!

permissions:
  ai.use:
    description: Allows use of basic AI commands
    default: true
  ai.admin:
    description: Allows administrative AI commands
    default: op
